project(PaddleOCRCppDemo CXX C)
cmake_minimum_required(VERSION 3.14)

SET(PaddleOCR_LIB "" CACHE PATH "Location of libraries")
set(PROJECT_NAME "CppDemo")
ADD_DEFINITIONS(-DUNICODE)

macro(safe_set_static_flag)
    foreach(flag_var
        CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
      if(${flag_var} MATCHES "/MD")
        string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
      endif(${flag_var} MATCHES "/MD")
    endforeach(flag_var)
endmacro()
 
if(NOT DEFINED PaddleOCR_LIB)
  message(FATAL_ERROR "please set PaddleOCR_LIB with -DPaddleOCR_LIB=/path/PaddleOCR")
endif()

include_directories("${PaddleOCR_LIB}")
link_directories("${PaddleOCR_LIB}/lib")

if (WIN32)
    set(CMAKE_C_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG} /bigobj /MTd ${FLAG_OPENMP}")
    set(CMAKE_C_FLAGS_RELEASE  "${CMAKE_C_FLAGS_RELEASE} /bigobj /MT ${FLAG_OPENMP}")
    set(CMAKE_CXX_FLAGS_DEBUG  "${CMAKE_CXX_FLAGS_DEBUG} /bigobj /MTd ${FLAG_OPENMP}")
    set(CMAKE_CXX_FLAGS_RELEASE   "${CMAKE_CXX_FLAGS_RELEASE} /bigobj /MT ${FLAG_OPENMP} ")

    if (WITH_STATIC_LIB)
        safe_set_static_flag()
        add_definitions(-DSTATIC_LIB)
    endif()
    message("cmake c debug flags " ${CMAKE_C_FLAGS_DEBUG})
    message("cmake c release flags " ${CMAKE_C_FLAGS_RELEASE})
    message("cmake cxx debug flags " ${CMAKE_CXX_FLAGS_DEBUG})
    message("cmake cxx release flags " ${CMAKE_CXX_FLAGS_RELEASE})
else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g  ${FLAG_OPENMP} -std=c++14")
    set(CMAKE_STATIC_LIBRARY_PREFIX "")
    message("cmake cxx flags" ${CMAKE_CXX_FLAGS})
    message("cmake cxx release flags " ${CMAKE_CXX_FLAGS_RELEASE})
endif()
include_directories("${CMAKE_SOURCE_DIR}/")
if(WITH_STATIC_LIB)
  if(WIN32)
    set(DEPS ${DEPS} ${PaddleOCR_LIB}/lib/PaddleOCR${CMAKE_STATIC_LIBRARY_SUFFIX})
  else()
   set(DEPS ${DEPS} ${PaddleOCR_LIB}/lib/PaddleOCR${CMAKE_SHARED_LIBRARY_SUFFIX})
  endif()
else()
  if(WIN32)
   set(DEPS ${DEPS} ${PaddleOCR_LIB}/lib/PaddleOCR${CMAKE_STATIC_LIBRARY_SUFFIX})
  else()
    set(DEPS ${DEPS} ${PaddleOCR_LIB}/lib/PaddleOCR${CMAKE_SHARED_LIBRARY_SUFFIX})
  endif()
endif(WITH_STATIC_LIB)
AUX_SOURCE_DIRECTORY(./src SRCS)
add_executable(${PROJECT_NAME}  ${SRCS})
target_link_libraries(${PROJECT_NAME} ${DEPS})
if (WIN32)
    add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
       COMMAND ${CMAKE_COMMAND} -E copy_if_different ${PROJECT_NAME}.exe ./release/${PROJECT_NAME}.exe
       COMMAND ${CMAKE_COMMAND} -E  copy_directory_if_different ../../win_runtime_x64 ./release/
    )
endif()